- hosts: terraform-ansible
  tasks:
    - name: criando o arquivo
      copy:
        dest: /home/ubuntu/index.html #
        content: <h1>Feito com terraform e ansible</h1>
    
    - name: criando o servidor
      shell: "nohup busybox hhtpd -f -p 8080 &"

#Executa com o: ansible-playbook playbook.yml -u ubuntu --private-key iac-alura.pem -i hosts
