- hosts: terraform-ansible
  tasks:
    - name: instalando o python e virtualenv
      apt:
        pkg: #pacotes a serem instalados
        - python3
        - virtualenv
        update_cache: yes
      become: yes


#Executa com o: ansible-playbook playbook.yml -u ubuntu --private-key iac-alura.pem -i hosts
