- hosts: terraform-ansible
  tasks:
    - name: instalando o python e virtualenv
      apt:
        pkg: #pacotes a serem instalados
        - python3
        - virtualenv
        update_cache: yes
      become: yes

    - name: instalando dependencias com o pip (Django e Django Rest)
      pip:
        virtualenv: /home/ubuntu/tcc/venv
        name: 
          - django 
          - djangorestframework

    - name: Iniciando projeto 
      shell: '. /home/ubuntu/tcc/venv/bin/activate; django-admin startproject setup /home/ubuntu/tcc/'

    - name: Alterando host do settings
      lineinfile: 
        path: /home/ubuntu/tcc/setup/settings.py
        regexp: 'ALLOWED_HOSTS'
        line: 'ALLOWED_HOSTS = ["*"]'
        backrefs: yes

#Executa com o: ansible-playbook playbook.yml -u ubuntu --private-key iac-alura.pem -i hosts
